INSERT INTO public.exercises (name, description, muscle_group, equipement, difficulty, is_cardio, default_rest_seconds) VALUES
-- Chest
('Barbell Bench Press', 'Primary compound lift for overall chest development.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Olympic bar', 'Intermediate', false, 90),
('Dumbbell Bench Press', 'Allows for a greater range of motion and unilateral development.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 75),
('Incline Barbell Press', 'Emphasizes the upper (clavicular) head of the pecs.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Olympic bar', 'Intermediate', false, 90),
('Incline Dumbbell Press', 'Excellent for targeting the upper chest and correcting imbalances.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 75),
('Decline Barbell Press', 'Emphasizes the lower (sternal) head of the pecs.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Olympic bar', 'Intermediate', false, 90),
('Decline Dumbbell Press', 'Targets the lower chest with dumbbells.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 75),
('Push-up', 'Fundamental bodyweight exercise for chest, shoulders, and triceps.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', NULL, 'Beginner', false, 60),
('Wide-Grip Push-up', 'Increases focus on the chest by widening hand placement.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', NULL, 'Beginner', false, 60),
('Decline Push-up', 'Increases difficulty and targets the upper chest.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', NULL, 'Intermediate', false, 60),
('Incline Push-up', 'Easier variation that reduces the percentage of bodyweight lifted.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', NULL, 'Beginner', false, 60),
('Dumbbell Fly', 'Isolation movement to stretch and contract the pecs.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Beginner', false, 60),
('Incline Dumbbell Fly', 'Isolation movement for the upper chest.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 60),
('Cable Crossover', 'Provides constant tension on the chest, excellent for inner pec development.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Cable machine', 'Intermediate', false, 60),
('Low-to-High Cable Fly', 'Targets the upper chest using a cable machine.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Cable machine', 'Intermediate', false, 60),
('Pec Deck Machine', 'Machine-based isolation fly for the chest.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Cable machine', 'Beginner', false, 60),
('Machine Chest Press', 'A guided compound press, good for beginners.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Weight bench', 'Beginner', false, 75),
('Incline Machine Press', 'Targets the upper chest using a machine.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Weight bench', 'Beginner', false, 75),
('Dumbbell Pullover', 'A unique exercise that stretches the lats and works the chest.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 75),
('Chest Dip', 'A compound bodyweight movement targeting the lower chest. Lean forward to emphasize pecs.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', NULL, 'Advanced', false, 90),
('Plate Press', 'An isometric-style press focusing on the inner chest squeeze.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Weight plates', 'Beginner', false, 60),

-- Back
('Barbell Deadlift', 'A full-body compound lift, heavily engaging the entire back.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Advanced', false, 120),
('Sumo Deadlift', 'A deadlift variation with a wide stance that engages more legs and hips.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Advanced', false, 120),
('Romanian Deadlift (RDL)', 'Focuses on the hamstrings, glutes, and lower back.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Olympic bar', 'Intermediate', false, 90),
('Dumbbell RDL', 'Unilateral variation of the Romanian Deadlift.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Dumbbells', 'Intermediate', false, 75),
('Pull-up', 'Bodyweight exercise for back width, primarily targeting the lats.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Advanced', false, 90),
('Wide-Grip Pull-up', 'Emphasizes the latissimus dorsi for a wider back.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Advanced', false, 90),
('Chin-up', 'Underhand grip pull-up that heavily involves the biceps.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Intermediate', false, 90),
('Neutral-Grip Pull-up', 'Palms facing each other, a more joint-friendly pull-up variation.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Intermediate', false, 90),
('Lat Pulldown', 'Machine-based alternative to pull-ups for back width.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Cable machine', 'Beginner', false, 75),
('Wide-Grip Lat Pulldown', 'Standard pulldown for lat development.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Cable machine', 'Beginner', false, 75),
('Close-Grip Lat Pulldown', 'Underhand or neutral grip to vary muscle engagement.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Cable machine', 'Beginner', false, 75),
('Bent-Over Barbell Row', 'A fundamental compound row for back thickness.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Intermediate', false, 90),
('Pendlay Row', 'A stricter variation of the barbell row where the bar rests on the floor between reps.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Advanced', false, 90),
('Single-Arm Dumbbell Row', 'Excellent for unilateral back development and correcting imbalances.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Dumbbells', 'Beginner', false, 75),
('T-Bar Row', 'A classic exercise for targeting the middle back.','Back (trapezius, rhomboids)', 'Olympic bar', 'Intermediate', false, 90),
('Seated Cable Row', 'A controlled movement for the middle back and lats.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Cable machine', 'Beginner', false, 75),
('Chest-Supported Dumbbell Row', 'Removes momentum and isolates the back muscles.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Dumbbells', 'Intermediate', false, 75),
('Inverted Row', 'A bodyweight rowing movement.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Beginner', false, 60),
('Straight-Arm Pulldown', 'An isolation exercise for the lats.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Cable machine', 'Intermediate', false, 60),
('Barbell Shrug', 'Targets the upper trapezius muscles.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Beginner', false, 60),
('Dumbbell Shrug', 'Isolates the traps using dumbbells.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Dumbbells', 'Beginner', false, 60),
('Good Morning', 'A hip-hinge movement for the posterior chain, especially lower back and hamstrings.', 'Lower back (erector spinae)', 'Olympic bar', 'Advanced', false, 90),
('Back Extension', 'Also known as hyperextension, it targets the lower back.', 'Lower back (erector spinae)', NULL, 'Beginner', false, 60),
('Renegade Row', 'A challenging core and back exercise combining a plank and a row.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Dumbbells', 'Advanced', false, 75),
('Rack Pull', 'A deadlift variation with a limited range of motion to focus on the upper back.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Intermediate', false, 100),

-- Shoulders
('Standing Barbell Overhead Press (OHP)', 'A core compound lift for building strong, broad shoulders.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Intermediate', false, 90),
('Seated Barbell Overhead Press', 'A stricter version of the OHP, removing leg drive.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Intermediate', false, 90),
('Seated Dumbbell Shoulder Press', 'Allows for a more natural range of motion.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 75),
('Arnold Press', 'A rotational dumbbell press that hits all three heads of the deltoid.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 75),
('Dumbbell Lateral Raise', 'The primary isolation exercise for the side delts, creating shoulder width.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Beginner', false, 60),
('Cable Lateral Raise', 'Provides constant tension on the side delt throughout the movement.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Cable machine', 'Intermediate', false, 60),
('Machine Lateral Raise', 'A guided version of the lateral raise.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Weight bench', 'Beginner', false, 60),
('Dumbbell Front Raise', 'Isolates the front deltoid.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Beginner', false, 60),
('Plate Front Raise', 'Using a weight plate to perform a front raise.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Weight plates', 'Beginner', false, 60),
('Cable Front Raise', 'Using a cable for constant tension on the front delts.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Cable machine', 'Beginner', false, 60),
('Bent-Over Dumbbell Rear Delt Raise', 'Isolates the posterior deltoids.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 60),
('Reverse Pec Deck', 'A machine-based exercise for the rear delts.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Cable machine', 'Beginner', false, 60),
('Face Pull', 'An excellent exercise for rear delt health and upper back posture.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Cable machine', 'Beginner', false, 60),
('Barbell Upright Row', 'A compound movement for traps and side delts.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Intermediate', false, 75),
('Dumbbell Upright Row', 'A dumbbell variation of the upright row.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 75),
('Push Press', 'An explosive overhead press using leg drive to lift heavier weight.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Advanced', false, 100),
('Landmine Press', 'A single-arm press variation that is joint-friendly.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Intermediate', false, 75),
('Pike Push-up', 'A bodyweight exercise that mimics an overhead press.', 'Shoulders / Deltoids (anterior, lateral, posterior)', NULL, 'Intermediate', false, 75),
('Handstand Push-up', 'An advanced bodyweight press for the shoulders.', 'Shoulders / Deltoids (anterior, lateral, posterior)', NULL, 'Advanced', false, 90),
('Bus Drivers', 'A rotational exercise with a weight plate for front delts and rotator cuffs.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Weight plates', 'Beginner', false, 45),

-- Legs
('Barbell Back Squat', 'The quintessential lower body exercise for strength and muscle.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Intermediate', false, 120),
('High-Bar Back Squat', 'A squat style with a more upright torso, emphasizing the quads.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Intermediate', false, 120),
('Low-Bar Back Squat', 'A squat style with more forward lean, emphasizing the posterior chain.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Front Squat', 'Places more emphasis on the quads and requires significant core strength.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Goblet Squat', 'A great introductory squatting movement using a dumbbell or kettlebell.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Beginner', false, 75),
('Dumbbell Squat', 'Holding two dumbbells at the sides while squatting.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Beginner', false, 75),
('Box Squat', 'Squatting down to a box to ensure consistent depth and build power.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Intermediate', false, 100),
('Leg Press', 'A stable machine alternative to squats for leg mass.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Leg press machine', 'Beginner', false, 90),
('Lunge', 'A unilateral exercise excellent for balance, glutes, and quads.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', NULL, 'Beginner', false, 75),
('Walking Lunge', 'A dynamic lunge variation.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Beginner', false, 75),
('Reverse Lunge', 'A lunge variation that is often easier on the knees.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Beginner', false, 75),
('Bulgarian Split Squat', 'An advanced single-leg squat variation.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Advanced', false, 90),
('Leg Extension', 'An isolation exercise for the quadriceps.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Leg extension machine', 'Beginner', false, 60),
('Lying Leg Curl', 'An isolation exercise for the hamstrings.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Leg curl machine', 'Beginner', false, 60),
('Seated Leg Curl', 'Another machine variation for isolating the hamstrings.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Leg curl machine', 'Beginner', false, 60),
('Glute Ham Raise (GHR)', 'An advanced bodyweight exercise for the hamstrings and glutes.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', NULL, 'Advanced', false, 90),
('Hip Thrust', 'A primary exercise for building glute strength and size.', 'Glutes (gluteus maximus, medius, minimus)', 'Olympic bar', 'Intermediate', false, 90),
('Dumbbell Hip Thrust', 'A dumbbell variation of the hip thrust.', 'Glutes (gluteus maximus, medius, minimus)', 'Dumbbells', 'Intermediate', false, 75),
('Glute Bridge', 'A bodyweight or weighted exercise for the glutes.', 'Glutes (gluteus maximus, medius, minimus)', NULL, 'Beginner', false, 60),
('Standing Calf Raise', 'Targets the gastrocnemius (upper calf).', 'Calves (gastrocnemius, soleus)', NULL, 'Beginner', false, 60),
('Seated Calf Raise', 'Targets the soleus (lower calf).', 'Calves (gastrocnemius, soleus)', NULL, 'Beginner', false, 60),
('Adductor Machine', 'Isolates the inner thigh muscles.', 'Adductors (adductor magnus, longus, pectineus)', 'Adductor/abductor machine', 'Beginner', false, 60),
('Abductor Machine', 'Isolates the outer thigh and glute muscles.', 'Abductors (tensor fasciae latae, gluteus medius)', 'Adductor/abductor machine', 'Beginner', false, 60),
('Hack Squat', 'A machine squat that reduces lower back strain.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Weight bench', 'Intermediate', false, 90),
('Kettlebell Swing', 'A powerful full-body explosive movement focusing on the posterior chain.', 'Glutes (gluteus maximus, medius, minimus)', 'Kettlebell', 'Intermediate', false, 75),
('Step-Up', 'A unilateral leg exercise performed by stepping onto a box or bench.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Beginner', false, 75),

-- Biceps
('Standing Barbell Curl', 'The classic mass builder for biceps.', 'Biceps (biceps brachii, brachialis)', 'Olympic bar', 'Beginner', false, 75),
('EZ-Bar Curl', 'An easier-on-the-wrists alternative to the barbell curl.', 'Biceps (biceps brachii, brachialis)', 'EZ-bar', 'Beginner', false, 75),
('Standing Dumbbell Curl', 'Allows for wrist supination for a peak contraction.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Beginner', false, 60),
('Alternating Dumbbell Curl', 'Performing curls one arm at a time.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Beginner', false, 60),
('Hammer Curl', 'Targets the brachialis and brachioradialis for overall arm thickness.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Beginner', false, 60),
('Incline Dumbbell Curl', 'Stretches the long head of the bicep for a unique stimulus.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Intermediate', false, 60),
('Seated Dumbbell Curl', 'A stricter curl variation.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Beginner', false, 60),
('Preacher Curl', 'Isolates the biceps by preventing body momentum.', 'Biceps (biceps brachii, brachialis)', 'EZ-bar', 'Intermediate', false, 60),
('Dumbbell Preacher Curl', 'Unilateral preacher curl.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Intermediate', false, 60),
('Concentration Curl', 'A strict isolation movement for the bicep peak.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Intermediate', false, 60),
('Cable Curl', 'Provides constant tension throughout the curl.', 'Biceps (biceps brachii, brachialis)', 'Cable machine', 'Beginner', false, 60),
('Reverse Grip Barbell Curl', 'Targets the brachioradialis and forearm extensors.', 'Forearms (flexors, extensors, pronators, supinators)', 'Olympic bar', 'Intermediate', false, 75),
('Zottman Curl', 'A unique curl combining a standard and reverse curl to work multiple arm muscles.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Advanced', false, 75),
('Spider Curl', 'Performed on an incline bench to isolate the biceps.', 'Biceps (biceps brachii, brachialis)', 'EZ-bar', 'Intermediate', false, 60),
('Drag Curl', 'A barbell curl variation where the bar is dragged up the body.', 'Biceps (biceps brachii, brachialis)', 'Olympic bar', 'Intermediate', false, 75),

-- Triceps
('Close-Grip Barbell Bench Press', 'A compound lift for triceps that allows for heavy weight.', 'Triceps (long, lateral, medial head)', 'Olympic bar', 'Intermediate', false, 90),
('Triceps Dip', 'A powerful bodyweight exercise for triceps mass. Keep torso upright.', 'Triceps (long, lateral, medial head)', NULL, 'Intermediate', false, 75),
('Bench Dip', 'A more accessible dip variation using a bench.', 'Triceps (long, lateral, medial head)', 'Weight bench', 'Beginner', false, 60),
('Lying Triceps Extension (Skull Crusher)', 'A classic triceps isolation exercise.', 'Triceps (long, lateral, medial head)', 'EZ-bar', 'Intermediate', false, 75),
('Dumbbell Skull Crusher', 'Using dumbbells for a more natural wrist position.', 'Triceps (long, lateral, medial head)', 'Dumbbells', 'Intermediate', false, 75),
('Cable Rope Triceps Pushdown', 'The most popular cable exercise for triceps.', 'Triceps (long, lateral, medial head)', 'Cable machine', 'Beginner', false, 60),
('V-Bar Triceps Pushdown', 'A pushdown variation using a V-bar.', 'Triceps (long, lateral, medial head)', 'Cable machine', 'Beginner', false, 60),
('Single-Arm Cable Pushdown', 'A unilateral pushdown to correct imbalances.', 'Triceps (long, lateral, medial head)', 'Cable machine', 'Beginner', false, 60),
('Overhead Dumbbell Extension', 'Targets the long head of the triceps with a great stretch.', 'Triceps (long, lateral, medial head)', 'Dumbbells', 'Beginner', false, 75),
('Cable Rope Overhead Extension', 'A cable version of the overhead extension.', 'Triceps (long, lateral, medial head)', 'Cable machine', 'Intermediate', false, 60),
('Dumbbell Kickback', 'A light isolation movement for the triceps.', 'Triceps (long, lateral, medial head)', 'Dumbbells', 'Beginner', false, 45),
('Diamond Push-up', 'A close-grip push-up that heavily targets the triceps.', 'Triceps (long, lateral, medial head)', NULL, 'Intermediate', false, 60),
('JM Press', 'A hybrid between a close-grip press and a skull crusher.', 'Triceps (long, lateral, medial head)', 'Olympic bar', 'Advanced', false, 90),
('Assisted Triceps Dip Machine', 'A machine to assist with bodyweight dips.', 'Triceps (long, lateral, medial head)', 'Assisted dip/pull-up machine', 'Beginner', false, 75),
('Reverse Grip Triceps Pushdown', 'A variation that targets the medial head of the triceps.', 'Triceps (long, lateral, medial head)', 'Cable machine', 'Intermediate', false, 60),

-- Forearms
('Barbell Wrist Curl', 'Targets the forearm flexors.', 'Forearms (flexors, extensors, pronators, supinators)', 'Olympic bar', 'Beginner', false, 45),
('Dumbbell Wrist Curl', 'Dumbbell variation of the wrist curl.', 'Forearms (flexors, extensors, pronators, supinators)', 'Dumbbells', 'Beginner', false, 45),
('Barbell Reverse Wrist Curl', 'Targets the forearm extensors.', 'Forearms (flexors, extensors, pronators, supinators)', 'Olympic bar', 'Beginner', false, 45),
('Farmer''s Walk', 'An exercise for grip strength and overall conditioning.', 'Forearms (flexors, extensors, pronators, supinators)', 'Dumbbells', 'Intermediate', false, 60),
('Plate Pinch', 'An exercise to develop pinch grip strength.', 'Forearms (flexors, extensors, pronators, supinators)', 'Weight plates', 'Intermediate', false, 45),
('Behind-the-Back Barbell Wrist Curl', 'A variation of the wrist curl for a greater stretch.', 'Forearms (flexors, extensors, pronators, supinators)', 'Olympic bar', 'Intermediate', false, 45),
('Grip Crusher', 'Using a hand gripper to improve crush grip strength.', 'Forearms (flexors, extensors, pronators, supinators)', NULL, 'Beginner', false, 30),

-- Abs & Core
('Crunch', 'A classic exercise targeting the upper abs.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Beginner', false, 45),
('Leg Raise', 'Targets the lower abdominals.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Beginner', false, 60),
('Hanging Leg Raise', 'An advanced variation of the leg raise for lower abs and hip flexors.', 'Abs (rectus abdominis, transverse abdominis)', 'Pull-up bar', 'Advanced', false, 75),
('Hanging Knee Raise', 'An easier version of the hanging leg raise.', 'Abs (rectus abdominis, transverse abdominis)', 'Pull-up bar', 'Intermediate', false, 60),
('Plank', 'An isometric core exercise for stability.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Beginner', false, 60),
('Side Plank', 'Targets the obliques and improves lateral core stability.', 'Obliques (internal and external)', NULL, 'Beginner', false, 60),
('Russian Twist', 'A rotational exercise for the obliques.', 'Obliques (internal and external)', 'Medicine ball', 'Beginner', false, 45),
('Bicycle Crunch', 'A dynamic crunch movement that engages the entire core.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Beginner', false, 45),
('Cable Crunch', 'Allows for progressive overload on the abdominal muscles.', 'Abs (rectus abdominis, transverse abdominis)', 'Cable machine', 'Intermediate', false, 60),
('Ab Wheel Rollout', 'A challenging anti-extension core exercise.', 'Abs (rectus abdominis, transverse abdominis)', 'Ab wheel', 'Advanced', false, 75),
('Wood Chopper (Cable)', 'A rotational movement for core and oblique strength.', 'Obliques (internal and external)', 'Cable machine', 'Intermediate', false, 60),
('Sit-up', 'A full range of motion exercise for the abs.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Beginner', false, 60),
('V-up', 'An advanced core exercise combining a sit-up and a leg raise.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Advanced', false, 60),
('Flutter Kicks', 'A dynamic exercise for the lower abs.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Beginner', false, 45),
('Decline Crunch', 'Increases the difficulty of a standard crunch.', 'Abs (rectus abdominis, transverse abdominis)', 'Weight bench', 'Intermediate', false, 45),

-- Cardio
('Treadmill Running', 'Cardiovascular exercise on a treadmill.', 'Cardio / Endurance (cardiovascular system)', 'Treadmill', 'Beginner', true, 0),
('Treadmill Walking (Incline)', 'Low-impact cardio with an emphasis on glutes and calves.', 'Cardio / Endurance (cardiovascular system)', 'Treadmill', 'Beginner', true, 0),
('Elliptical Trainer', 'Low-impact, full-body cardiovascular workout.', 'Cardio / Endurance (cardiovascular system)', 'Elliptical trainer', 'Beginner', true, 0),
('Stationary Bike', 'Cardiovascular exercise focused on the lower body.', 'Cardio / Endurance (cardiovascular system)', 'Air bike', 'Beginner', true, 0),
('Rowing Machine', 'A full-body cardio workout that also builds back and leg endurance.', 'Cardio / Endurance (cardiovascular system)', 'Rowing machine', 'Intermediate', true, 0),
('Jump Rope', 'High-intensity cardio that improves coordination and agility.', 'Cardio / Endurance (cardiovascular system)', 'Jump rope', 'Intermediate', true, 0),
('Stair Stepper', 'Simulates climbing stairs for a high-intensity lower body cardio workout.', 'Cardio / Endurance (cardiovascular system)', 'Stair stepper', 'Intermediate', true, 0),
('Battle Ropes', 'A high-intensity upper body and core conditioning tool.', 'Cardio / Endurance (cardiovascular system)', 'Battle rope', 'Advanced', true, 0),
('Box Jumps', 'A plyometric exercise for explosive power and conditioning.', 'Cardio / Endurance (cardiovascular system)', 'Plyometric box', 'Advanced', true, 0),
('Burpees', 'A full-body conditioning exercise.', 'Cardio / Endurance (cardiovascular system)', NULL, 'Intermediate', true, 0),
('Jumping Jacks', 'A classic warm-up and light cardio exercise.', 'Cardio / Endurance (cardiovascular system)', NULL, 'Beginner', true, 0),
('High Knees', 'A dynamic warm-up and cardio drill.', 'Cardio / Endurance (cardiovascular system)', NULL, 'Beginner', true, 0),
('Mountain Climbers', 'A core and cardio exercise in a plank position.', 'Cardio / Endurance (cardiovascular system)', NULL, 'Intermediate', true, 0),
('Kettlebell Swings', 'An explosive cardio and strength exercise.', 'Cardio / Endurance (cardiovascular system)', 'Kettlebell', 'Intermediate', true, 0),
('Sled Push', 'A full-body strength and conditioning exercise.', 'Cardio / Endurance (cardiovascular system)', NULL, 'Advanced', true, 0),

-- Full Body / Miscellaneous
('Clean and Jerk', 'An Olympic weightlifting movement for total body power.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Elite', false, 180),
('Snatch', 'An Olympic weightlifting movement requiring speed, power, and coordination.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Elite', false, 180),
('Turkish Get-Up', 'A complex, full-body movement for stability and strength.', 'Abs (rectus abdominis, transverse abdominis)', 'Kettlebell', 'Advanced', false, 90),
('Thruster', 'A combination of a front squat and a push press.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Wall Ball', 'A squat and throw movement for conditioning.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Medicine ball', 'Intermediate', true, 0),
('Bodyweight Squat', 'The fundamental squat movement without added weight.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', NULL, 'Beginner', false, 60),
('Glute Kickback (Cable)', 'An isolation exercise for the glutes using a cable machine.', 'Glutes (gluteus maximus, medius, minimus)', 'Cable machine', 'Beginner', false, 45),
('Calf Press on Leg Press Machine', 'Using the leg press to train calves.', 'Calves (gastrocnemius, soleus)', 'Leg press machine', 'Beginner', false, 60),
('Seated Overhead Dumbbell Press', 'Shoulder press performed while seated.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 75),
('Standing Biceps Cable Curl', 'Biceps curl using a cable machine.', 'Biceps (biceps brachii, brachialis)', 'Cable machine', 'Beginner', false, 60),
('Smith Machine Bench Press', 'A guided version of the bench press.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Smith machine', 'Beginner', false, 75),
('Smith Machine Squat', 'A guided squat.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Smith machine', 'Beginner', false, 90),
('EZ-Bar Skull Crusher', 'Skull crusher using an EZ-bar for wrist comfort.', 'Triceps (long, lateral, medial head)', 'EZ-bar', 'Intermediate', false, 75),
('Single Leg RDL', 'A unilateral Romanian Deadlift for balance and hamstring strength.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Dumbbells', 'Advanced', false, 75),
('Pistol Squat', 'An advanced, single-leg bodyweight squat.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', NULL, 'Advanced', false, 120),
('Muscle-up', 'An advanced gymnastic movement combining a pull-up and a dip.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Elite', false, 150),
('Front Lever', 'An advanced isometric hold for back and core strength.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Elite', false, 90),
('Back Lever', 'An advanced isometric hold for pulling muscles and core.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Pull-up bar', 'Elite', false, 90),
('L-Sit', 'An isometric core exercise.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Advanced', false, 60),
('Box Squat (Dumbbell)', 'Performing a box squat holding dumbbells.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Intermediate', false, 75),
('Single Leg Press', 'Performing the leg press with one leg at a time.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Leg press machine', 'Intermediate', false, 90),
('Walking Dumbbell Lunge', 'Dynamic lunge variation.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Dumbbells', 'Beginner', false, 75),
('Cross Body Hammer Curl', 'A hammer curl performed across the body.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Beginner', false, 60),
('Decline Dumbbell Fly', 'Flyes on a decline bench to target the lower chest.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 60),
('Seated Arnold Press', 'The Arnold Press performed while seated for stricter form.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 75),
('Incline Hammer Curl', 'Hammer curls on an incline bench.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Intermediate', false, 60),
('Kneeling Cable Crunch', 'A weighted crunch using a cable machine.', 'Abs (rectus abdominis, transverse abdominis)', 'Cable machine', 'Intermediate', false, 60),
('Landmine Squat', 'A squat variation using a landmine setup.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Intermediate', false, 75),
('One-Arm Lat Pulldown', 'A unilateral pulldown to focus on each lat individually.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Cable machine', 'Intermediate', false, 60),
('Sissy Squat', 'An advanced bodyweight squat that heavily isolates the quads.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', NULL, 'Advanced', false, 75),
('Spider Crawl', 'A dynamic plank variation for core and mobility.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Intermediate', false, 60),
('Superman', 'An exercise for strengthening the lower back.', 'Lower back (erector spinae)', NULL, 'Beginner', false, 45),
('Tate Press', 'A triceps exercise similar to a skull crusher but with a different angle.', 'Triceps (long, lateral, medial head)', 'Dumbbells', 'Advanced', false, 75),
('Zercher Squat', 'A squat variation where the bar is held in the crook of the elbows.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Clean', 'The first part of the Clean and Jerk, for explosive power.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Jerk', 'The second part of the Clean and Jerk, an overhead explosive movement.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Advanced', false, 120),
('Power Clean', 'A variation of the clean focused on power development.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Hang Clean', 'A clean variation starting from a standing "hang" position.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Advanced', false, 120),
('Barbell Hip Abduction', 'Targets the gluteus medius and minimus.', 'Abductors (tensor fasciae latae, gluteus medius)', 'Olympic bar', 'Intermediate', false, 60),
('Banded Glute Bridge', 'A glute bridge with a resistance band around the knees.', 'Glutes (gluteus maximus, medius, minimus)', 'Resistance bands', 'Beginner', false, 60),
('Banded Lateral Walk', 'Targets the hip abductors using a resistance band.', 'Abductors (tensor fasciae latae, gluteus medius)', 'Resistance bands', 'Beginner', false, 45),
('Boxer Skip', 'A jump rope variation for cardio and coordination.', 'Cardio / Endurance (cardiovascular system)', 'Jump rope', 'Intermediate', true, 0),
('Cable Pull-Through', 'A hip hinge movement that targets the glutes and hamstrings.', 'Glutes (gluteus maximus, medius, minimus)', 'Cable machine', 'Intermediate', false, 75),
('Clapping Push-up', 'A plyometric push-up for explosive chest power.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', NULL, 'Advanced', false, 75),
('Cossack Squat', 'A squat variation that improves hip mobility and unilateral leg strength.', 'Adductors (adductor magnus, longus, pectineus)', NULL, 'Advanced', false, 90),
('Dumbbell Floor Press', 'A bench press variation with a limited range of motion.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 75),
('Dumbbell Snatch', 'A single-arm explosive movement for full-body power.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Advanced', false, 90),
('Frog Pumps', 'A glute isolation exercise.', 'Glutes (gluteus maximus, medius, minimus)', NULL, 'Beginner', false, 45),
('Jefferson Curl', 'A loaded stretch for the entire posterior chain.', 'Lower back (erector spinae)', 'Kettlebell', 'Advanced', false, 120),
('Kettlebell Goblet Squat', 'The classic goblet squat performed with a kettlebell.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Kettlebell', 'Beginner', false, 75),
('Nordic Hamstring Curl', 'A very challenging bodyweight exercise for the hamstrings.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', NULL, 'Elite', false, 120),
('Pallof Press', 'An anti-rotation core exercise.', 'Obliques (internal and external)', 'Cable machine', 'Intermediate', false, 60),
('Reverse Hyperextension', 'Targets the glutes and lower back.', 'Lower back (erector spinae)', 'Weight bench', 'Intermediate', false, 75),
('Ring Dips', 'Dips performed on gymnastic rings, requiring more stability.', 'Triceps (long, lateral, medial head)', NULL, 'Advanced', false, 90),
('Ring Rows', 'Inverted rows using gymnastic rings.', 'Back (latissimus dorsi, trapezius, rhomboids)', NULL, 'Intermediate', false, 60),
('Single-Leg Box Jump', 'An advanced plyometric jump.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Plyometric box', 'Advanced', true, 0),
('Tuck Jumps', 'A plyometric exercise for lower body power.', 'Cardio / Endurance (cardiovascular system)', NULL, 'Intermediate', true, 0),
('Windshield Wipers', 'An advanced core exercise for the obliques.', 'Obliques (internal and external)', NULL, 'Advanced', false, 60),
('Yates Row', 'A barbell row variation with a more upright torso.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Intermediate', false, 90),
('Air Squat', 'A simple bodyweight squat.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', NULL, 'Beginner', false, 45),
('Band Pull-Apart', 'A great exercise for shoulder health and upper back.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Resistance bands', 'Beginner', false, 30),
('Bodyweight Calf Raise', 'Calf raises using only bodyweight.', 'Calves (gastrocnemius, soleus)', NULL, 'Beginner', false, 45),
('Close-Grip Push-up', 'Push-up variation for triceps.', 'Triceps (long, lateral, medial head)', NULL, 'Intermediate', false, 60),
('Dragon Flag', 'An extremely advanced core exercise.', 'Abs (rectus abdominis, transverse abdominis)', NULL, 'Elite', false, 90),
('Dumbbell Bench Pull', 'A row variation performed lying face down on a bench.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Dumbbells', 'Intermediate', false, 75),
('Hammer Strength Chest Press', 'Chest press on a Hammer Strength machine.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Weight bench', 'Beginner', false, 75),
('Hammer Strength Row', 'Row on a Hammer Strength machine.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Weight bench', 'Beginner', false, 75),
('Incline Dumbbell Curl (Seated)', 'Strict incline curls.', 'Biceps (biceps brachii, brachialis)', 'Dumbbells', 'Intermediate', false, 60),
('Machine Preacher Curl', 'Preacher curls on a machine.', 'Biceps (biceps brachii, brachialis)', 'Weight bench', 'Beginner', false, 60),
('Medicine Ball Slam', 'An explosive cardio and power exercise.', 'Cardio / Endurance (cardiovascular system)', 'Medicine ball', 'Intermediate', true, 0),
('Overhead Squat', 'A squat with the barbell held overhead, requiring immense mobility.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Elite', false, 120),
('Reverse Barbell Lunge', 'Lunges stepping backward with a barbell.', 'Quadriceps (vastus medialis, lateralis, rectus femoris)', 'Olympic bar', 'Intermediate', false, 90),
('Side Lunge', 'A lunge performed to the side, targeting adductors and quads.', 'Adductors (adductor magnus, longus, pectineus)', NULL, 'Beginner', false, 60),
('Single-Arm Overhead Press (Dumbbell)', 'Unilateral overhead press with a dumbbell.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Dumbbells', 'Intermediate', false, 75),
('Smith Machine Incline Press', 'Incline press on a Smith machine.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Smith machine', 'Beginner', false, 75),
('Split Jerk', 'The Olympic lifting style of jerk.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Elite', false, 120),
('Stiff-Legged Deadlift', 'A deadlift variation focusing on the hamstrings.', 'Hamstrings (biceps femoris, semitendinosus, semimembranosus)', 'Olympic bar', 'Intermediate', false, 90),
('Trap Bar Deadlift', 'A deadlift using a trap bar, which is often easier on the lower back.', 'Back (latissimus dorsi, trapezius, rhomboids)', 'Olympic bar', 'Intermediate', false, 120),
('Weighted Crunch', 'Crunches performed while holding a weight.', 'Abs (rectus abdominis, transverse abdominis)', 'Weight plates', 'Intermediate', false, 60),
('Weighted Plank', 'A plank with a weight plate on the back.', 'Abs (rectus abdominis, transverse abdominis)', 'Weight plates', 'Advanced', false, 60),
('Z-Press', 'A seated overhead press performed on the floor.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Olympic bar', 'Advanced', false, 90),
('Cable Reverse Fly', 'A cable machine exercise for the rear delts.', 'Shoulders / Deltoids (anterior, lateral, posterior)', 'Cable machine', 'Intermediate', false, 60),
('Dumbbell Pullover (Cross Bench)', 'Pullover performed across a bench for greater stretch.', 'Chest (pectoralis major, lower pectoral, upper pectoral)', 'Dumbbells', 'Intermediate', false, 75);
