"""Add day_of_week to workouts table

Revision ID: c25b97220734
Revises: 
Create Date: 2025-10-17 18:03:01.078214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c25b97220734'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('exercises', 'is_cardio',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('exercises_name_key', 'exercises', type_='unique')
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.alter_column('user_exercise_logs', 'weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_exercise_logs', 'distance_m',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_exercise_logs', 'volume',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('user_exercise_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_user_exercise_logs_date', table_name='user_exercise_logs')
    op.drop_index('idx_user_exercise_logs_exercise', table_name='user_exercise_logs')
    op.drop_index('idx_user_exercise_logs_user', table_name='user_exercise_logs')
    op.drop_index('idx_user_exercise_logs_user_exercise_date', table_name='user_exercise_logs')
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'weight_kg',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'body_fat',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_exercises', 'planned_weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('workout_exercises', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('workouts', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workouts', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('workouts', 'day_of_week',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint('workouts_user_id_fkey', 'workouts', type_='foreignkey')
    op.create_foreign_key(None, 'workouts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workouts', type_='foreignkey')
    op.create_foreign_key('workouts_user_id_fkey', 'workouts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workouts', 'day_of_week',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('workouts', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workouts', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workout_exercises', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('workout_exercises', 'planned_weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'body_fat',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('users', 'weight_kg',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('users', 'birthdate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.create_index('idx_user_exercise_logs_user_exercise_date', 'user_exercise_logs', ['user_id', 'exercise_id', 'date'], unique=False)
    op.create_index('idx_user_exercise_logs_user', 'user_exercise_logs', ['user_id'], unique=False)
    op.create_index('idx_user_exercise_logs_exercise', 'user_exercise_logs', ['exercise_id'], unique=False)
    op.create_index('idx_user_exercise_logs_date', 'user_exercise_logs', ['date'], unique=False)
    op.alter_column('user_exercise_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_exercise_logs', 'volume',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('user_exercise_logs', 'distance_m',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('user_exercise_logs', 'weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.create_unique_constraint('exercises_name_key', 'exercises', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('exercises', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercises', 'is_cardio',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('exercises', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
