"""Change day_of_week to integer in workouts table

Revision ID: c31b2bb628f2
Revises: 1a72ff9bfdd7
Create Date: 2025-10-20 00:14:52.159661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31b2bb628f2'
down_revision: Union[str, None] = '1a72ff9bfdd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'day_of_week',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               postgresql_using='day_of_week::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'day_of_week',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
